Areas/Admin/Pages/User/AddRole.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using R10.models;

namespace R10.Admin.user
{
    public class AddRoleModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly MyBlogContext _context;

        public AddRoleModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            MyBlogContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        /// 
   
        // [BindProperty]
        // public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>


        public AppUser user { set; get; }

        [BindProperty]
        [Display(Name = "Các role cho user")]
        public string[] RoleNames { set; get; }

        public SelectList allRoles { set; get; }

        public List<IdentityRoleClaim<string>> claimInRole {set; get;}
        public List<IdentityUserClaim<string>> claimInUserRole {set; get;}

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("ko thay");
            }
            user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound($"KO co Tai khoan");
            }

            RoleNames = (await _userManager.GetRolesAsync(user)).ToArray<string>();

            List<string> roleNames = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            allRoles = new SelectList(roleNames);

            await GetClaim(id);
            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("ko thay");
            }
            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound($"KO co Tai khoan");
            }

            await GetClaim(id);

            //Rolesname
            var OldRoleNames = (await _userManager.GetRolesAsync(user)).ToArray();

            var deleRole = OldRoleNames.Where(r => !RoleNames.Contains(r));
            var addRole = RoleNames.Where(r => !OldRoleNames.Contains(r));

            List<string> roleNames = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            allRoles = new SelectList(roleNames);

            var resultDelete = await _userManager.RemoveFromRolesAsync(user, deleRole);
            if (!resultDelete.Succeeded)
            {
                resultDelete.Errors.ToList().ForEach(er =>
                {
                    ModelState.AddModelError(string.Empty, er.Description);
                });
                return Page();
            }

            var resultAdd = await _userManager.AddToRolesAsync(user, addRole);
            if (!resultAdd.Succeeded)
            {
                resultAdd.Errors.ToList().ForEach(er =>
                {
                    ModelState.AddModelError(string.Empty, er.Description);
                });
                return Page();
            }

            
            StatusMessage = $"Vừa cập nhật thành công {user.UserName}.";

            return RedirectToPage("./Index");
        }


        async Task GetClaim(string id)
        {
            var listRole = from r in _context.Roles
                            join ur in _context.UserRoles on r.Id equals ur.RoleId
                            where ur.UserId == id
                            select r;

            var _claimInrole = from c in _context.RoleClaims
                                join r in _context.Roles on c.RoleId equals r.Id
                                select c;

            claimInRole = await _claimInrole.ToListAsync();

            claimInUserRole = await (from u in _context.UserClaims
                                        where u.UserId == id select u).ToListAsync();

        }
    }
}

Areas/Admin/Pages/User/EditUserRoleClaim.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using R10.models;

namespace R10.Admin.user
{
    public class EditUserRoleClaimModel : PageModel
    {
        private readonly MyBlogContext _context;
        private readonly UserManager<AppUser> _userManager;

        public EditUserRoleClaimModel(
                MyBlogContext context,
                UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { set; get; }
        [BindProperty]
        public InputModel Input { set; get; }
        public class InputModel
        {
            [Display(Name = "ClaimType")]
            [Required(ErrorMessage = "{0} phải nhập")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "Tối thiểu {2} - {1} kí tự")]
            public string ClaimType { set; get; }

            [Display(Name = "ClaimValue")]
            [Required(ErrorMessage = "{0} phải nhập")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "Tối thiểu {2} - {1} kí tự")]
            public string ClaimValue { set; get; }
        }

        public AppUser user { set; get; }
        public IdentityUserClaim<string> userclaim {set; get;}
        public NotFoundObjectResult OnGet() => NotFound("ko truy cập");

        public async Task<IActionResult> OnGetAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);
            if (user == null) return NotFound("ko tim thay");

            return Page();
        }
        public async Task<IActionResult> OnPostAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);
            if (user == null) return NotFound("ko tim thay");

            if (!ModelState.IsValid) return Page();

            var claims = _context.UserClaims.Where(c => c.UserId == userid);

            if (claims.Any(c => c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue))
            {
                ModelState.AddModelError(string.Empty, "User Đã có đặc tính này");
                return Page();
            }

            var result = await _userManager.AddClaimAsync(user, new Claim(Input.ClaimType, Input.ClaimValue));
            if (!result.Succeeded)
            {
                result.Errors.ToList().ForEach(err =>{
                    ModelState.AddModelError(string.Empty, err.Description);
                });
            }
            StatusMessage = "Thêm thành công đặc tính";
            return RedirectToPage("./AddRole", new{ id = user.Id});
        }

        public async Task<IActionResult> OnGetEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("ko tim thay");
            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();

            user = await _userManager.FindByIdAsync(userclaim.UserId);
            if (user == null) return NotFound("ko tim thay");

            Input = new InputModel()
            {
                ClaimType = userclaim.ClaimType,
                ClaimValue = userclaim.ClaimValue
            };

            return Page();
        }
        public async Task<IActionResult> OnPostEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("ko tim thay");
            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();

            user = await _userManager.FindByIdAsync(userclaim.UserId);
            if (user == null) return NotFound("ko tim thay");

            if(!ModelState.IsValid) return Page();


            if(_context.UserClaims.Any(c => c.UserId == user.Id && 
                                         c.ClaimType == Input.ClaimType && 
                                         c.ClaimValue == Input.ClaimValue &&
                                         c.Id != userclaim.Id))
            {
                ModelState.AddModelError(string.Empty, "User Đã có đặc tính này");
                return Page();
            }

            userclaim.ClaimType = Input.ClaimType;
            userclaim.ClaimValue = Input.ClaimValue;

            await _context.SaveChangesAsync();

            StatusMessage = "Cập nhật thành công đặc tính";
            return RedirectToPage("./AddRole", new{ id = user.Id});
        }

         public async Task<IActionResult> OnPostDeleteClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("ko tim thay");
            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();

            user = await _userManager.FindByIdAsync(userclaim.UserId);
            if (user == null) return NotFound("ko tim thay");

            await _userManager.RemoveClaimAsync(user, new Claim(Input.ClaimType, Input.ClaimValue));

            StatusMessage = "Xoa thành công đặc tính";
            return RedirectToPage("./AddRole", new{ id = user.Id});
        }
    }
}

Areas/Admin/Pages/User/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using R10.models;

namespace R10.Admin.user
{
    public class IndexModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        [TempData]
        public string StatusMessage {set; get;}

        public const int Item_per_Page = 20;

        [BindProperty(SupportsGet = true, Name = "p")]
        public int currentPage { set; get; }

        public int countPages { set; get; }
        public IndexModel(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public int totalUser {set; get;}

        public class UserAndRole : AppUser
        {
            public string RoleNames {set; get;}
        }
        // public List<AppUser> users {set; get;}
        public List<UserAndRole> users {set; get;}
        public async Task OnGet()
        {
            // users = await _userManager.Users.OrderBy(u => u.UserName).ToListAsync();
             var qr = _userManager.Users.OrderBy(u => u.UserName);


            totalUser = await qr.CountAsync();
            countPages = (int)Math.Ceiling((double)totalUser / Item_per_Page);

            if (currentPage <1)
            {
                currentPage = 1;
            }
            if (currentPage > countPages)
            {
                currentPage = countPages;
            }

            var qr1 = (from a in _userManager.Users
                     orderby a.UserName 
                     select a)
                     .Skip((currentPage -1) *10)
                     .Take(Item_per_Page)
                     .Select(u => new UserAndRole(){
                         Id = u.Id,
                         UserName = u.UserName
                     });

            users = await qr1.ToListAsync();

            foreach (var item in users)
            {
                var roles = await _userManager.GetRolesAsync(item);
                item.RoleNames = string.Join(",", roles);
            }
        }

        public void OnPost() => RedirectToPage();
    }
}

Areas/Admin/Pages/User/SetPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using R10.models;

namespace R10.Admin.user
{
    public class SetPasswordModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SetPasswordModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public AppUser user {set; get;}

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("ko thay");
            }
            user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound($"KO co Tai khoan");
            }

            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("ko thay");
            }
            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound($"KO co Tai khoan");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            await _userManager.RemovePasswordAsync(user);

            var addPasswordResult = await _userManager.AddPasswordAsync(user, Input.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                foreach (var error in addPasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            // await _signInManager.RefreshSignInAsync(user);
            StatusMessage = $"Vừa cập nhật thành công {user.UserName}.";

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/User/AddRole.cshtml
@page "/admin/add-role/{id}"
@model AddRoleModel
@{
    ViewData["Title"] = "Thêm vai trò";
}

<h2>@ViewData["Title"]: @Model.user.UserName</h2>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleNames" ></label>
                @Html.ListBoxFor(m => m.RoleNames, Model.allRoles, new{
                    id = "id-select-role",
                    @class = "w-100"
                })
                <span asp-validation-for="RoleNames" class="text-danger"></span>
            </div>
            
            <button type="submit" class="w-100 btn btn-lg btn-primary mt-2">Cập nhật</button>
            <a asp-page="./Index" class="btn btn-primary mt-2" >Danh sách user</a>
        </form>
        <hr>
        <p> Các Claim của user có từ role</p>
        @if (Model.claimInRole.Count > 0)
        {
            <ul>
                @foreach (var claim in Model.claimInRole)
                {
                    <li>@claim.ClaimType: @claim.ClaimValue</li>
                }
            </ul>
        }
        <hr>
        <p> Các Claim của riêng user:
            <a asp-page="./EditUserRoleClaim" asp-page-handler="AddClaim" asp-route-userid="@Model.user.Id" >+ Thêm Claim riêng của user </a>    
        </p>
        @if (Model.claimInUserRole.Count > 0)
        {
            <ul>
                @foreach (var claim in Model.claimInUserRole)
                {                    
                    <li>
                        <a asp-page="./EditUserRoleClaim" asp-page-handler="EditClaim" asp-route-claimid="@claim.Id" >       
                            @claim.ClaimType: @claim.ClaimValue
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
</div>

@section Scripts {

    <script src="~/lib/multiple-select/multiple-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multiple-select/multiple-select.min.css">

    <script>
        $("#id-select-role").multipleSelect({
            selectAll: false,
            keepOpen: false,
            isOpen: false,
        });
    </script>

    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Pages/User/EditUserRoleClaim.cshtml
@page   "/admin/edit-user-claim/{userid?}"
@model R10.Admin.user.EditUserRoleClaimModel
@{
    ViewData["Title"] = "Thêm claim của user";
}

<h2>@ViewData["Title"]: @Model.user.UserName</h2>

<partial name="_StatusMessage" model = "@Model.StatusMessage"></partial>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.ClaimType" class="control-label"></label>
                <input asp-for="Input.ClaimType" class="form-control" />
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimValue" class="control-label"></label>
                <input asp-for="Input.ClaimValue" class="form-control" />
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>

            <div class="form-group">
                @if (Model.userclaim == null)
                {                    
                    <input type="submit" value="Create" class="btn btn-primary" />
                } 
                else
                {
                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    <input type="submit" value="Delete" class="btn btn-danger" asp-route-claimid="@Model.userclaim.Id" asp-page-handler="DeleteClaim" />
                    
                }
                <a class="btn btn-success" asp-page="./AddRole" asp-route-id = "@Model.user.Id" > Quay lại user</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Pages/User/Index.cshtml
@page "/admin/member"
@model R10.Admin.user.IndexModel
@{
    ViewData["Title"] = "Danh sách Thành viên";
}

@{
    var pagingModel = new R10.Helper.PagingModel()
    {
        currentPage = Model.currentPage,
        countPages = Model.countPages,
        generateUrl = (int? p) => @Url.Page("/User/Index", new { p })
    };
}


<h2>@ViewData["Title"]</h2>
<p>Tổng số thành viên: @Model.totalUser</p>

<partial name="_StatusMessage" model="@Model.StatusMessage"></partial>


@* <div class="mb-2">
    <a class="btn btn-secondary" asp-page="./Create">Thêm</a>
</div> *@

<partial name="_PagingTT" model="@pagingModel"></partial>

<table class="table">
    <tr>
        <th>Tên User</th>
        <th>Vai trò</th>
        <th>Tác vụ</th>
    </tr>

    @foreach (var item in Model.users)
    {
        <tr>
            <td>@item.UserName</td>
            <td>
                @if (string.IsNullOrEmpty(@item.RoleNames))
                {
                    <a class="text-dark text-decoration-none" asp-page="./AddRole" asp-route-id = "@item.Id" >+ Role</a>
                } else 
                {
                    <a class="text-decoration-none" asp-page="./AddRole" asp-route-id = "@item.Id" >@item.RoleNames</a>
                }
            </td>
            <td>

                <a class="btn btn-success btn-sm" asp-page="./SetPassword" asp-route-id="@item.Id">Đặt mật khẩu</a>
            </td>
        </tr>
    }
</table>

Areas/Admin/Pages/User/SetPassword.cshtml
@page "admin/setpassword/{id}"
@model SetPasswordModel
@{
    ViewData["Title"] = "Set password";
}

<h3>Dặt mật khẩu cho: @Model.user.UserName</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating">
                <input asp-for="Input.NewPassword" class="form-control" autocomplete="new-password" />
                <label asp-for="Input.NewPassword" class="form-label"></label>
                <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <input asp-for="Input.ConfirmPassword" class="form-control" autocomplete="new-password" />
                <label asp-for="Input.ConfirmPassword" class="form-label"></label>
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="w-100 btn btn-lg btn-primary">Đặt mật khẩu</button>
            <a asp-page="./Index" class="btn btn-primary mt-2" >Danh sách user</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}